### ISSUE TITLE
Metadata for Quicklisp

### ISSUE THREAD

**Issue by hydandata** [3b/classimp#10]
Please consider adding :description, :author and :license information to your ASDF system(s). This will greatly help Quicklisp users and make it easier for them to report bugs.

More information:

http://blog.quicklisp.org/2015/05/looking-for-more-metadata.html
https://www.quicklisp.org

**Comment by krdluzni** [comment]
Please consider adding license info to the project, even if not to the asdf system.  Without any license, this project is effectively closed to the public and left under copyright by default.
