### ISSUE TITLE
assimp4 support?

### ISSUE THREAD

**Issue by slyrus** [3b/classimp#15]
It looks like only versions 3.0-3.3.x are supported and my OS (Ubuntu 18.04) only seems to support version 4. Any chance classimp can work with that?
thanks!

**Comment by 3b** [comment]
https://github.com/3b/classimp/tree/dev adds 4.0, 4.1, and 5.0 support, with limited testing on 4.1 and 5.0.1 on win64. If nobody reports any problems, I will try to release it to QL within a month or so.

**Comment by 3b** [comment]
released fixes to master, closing
