### ISSUE TITLE
Problems loading and running on WIndows 10

### ISSUE THREAD

**Issue by maufdez** [3b/classimp#16]
Hi,
I have some problems getting classimp to work on windows, for starters it looks for assimp.dll or libassimp.dll when the name of the library on windows is assimp-vc140-mt.dll, then at some point it complains about the classimp only supporting 3.xx but when I built the latest 3.3.1 it does not work, however it does load with 4.1.0.
Another thing is that when I got it to load it gave me the following error (SBCL 64bits):

classimp was compiled for assimp version UNKNOWN, current assimp version is 4.1
   [Condition of type SIMPLE-ERROR]

I've tried re-installing, assimp several times, I have not tried compiling assimp from scratch, because I don't want to install visual studio, but I might try it if that would solve the problem.

Thanks!

**Comment by maufdez** [comment]
By the way the restart "Try using it anyway" does not work.

**Comment by maufdez** [comment]
This is the message I get when I rename the dll (as assimp.dll) and move it to my project's directory

trying to link against unsupported version of assimp. 3.0-3.3.x supported, got version 4.1
   [Condition of type SIMPLE-ERROR]

However it worked before I made that by giving the full path to the library using the appropriate restart.

**Comment by 3b** [comment]
sorry for the slow response, but https://github.com/3b/classimp/tree/dev should work with newer .dlls, and the version checks should work a bit better.

**Comment by 3b** [comment]
added missing dll names to search, and released fixes for newer .dll and broken version checks, please open new bugs if i missed any other problems
