### ISSUE TITLE
support for post processor flag parameters

### ISSUE THREAD

**Issue by axionix** [3b/classimp#9]
Some post-procesing flags require input parameters to control how they function. For example, remove-component requires you to specify a bitwise integer of which components to remove. Currently, there is no way to use the flags I am interested in (remove-component and gen-smooth-normals).

**Comment by 3b** [comment]
some of it was already there i think, but added a nicer API: you can pass a list of properties to `ai:import-into-lisp` now, and it should handle most of the complexity for you
